export const REQUEST_ALL_MOVIES_PENDING = "REQUEST_ALL_MOVIES_PENDING"
export const REQUEST_ALL_MOVIES_SUCCESS = "REQUEST_ALL_MOVIES_SUCCESS"
export const REQUEST_ALL_MOVIES_FAILED = "REQUEST_ALL_MOVIES_FAILED"

export const REQUEST_TRENDING_PENDING = "REQUEST_TRENDING_PENDING"
export const REQUEST_TRENDING_SUCCESS = "REQUEST_TRENDING_SUCCESS"
export const REQUEST_TRENDING_FAILED = "REQUEST_TRENDING_FAILED"

export const REQUEST_POPULAR_PENDING = "REQUEST_POPULAR_PENDING"
export const REQUEST_POPULAR_SUCCESS = "REQUEST_POPULAR_SUCCESS"
export const REQUEST_POPULAR_FAILED = "REQUEST_POPULAR_FAILED"

export const REQUEST_NEW_RELEASE_PENDING = "REQUEST_NEW_RELEASE_PENDING"
export const REQUEST_NEW_RELEASE_SUCCESS = "REQUEST_NEW_RELEASE_SUCCESS"
export const REQUEST_NEW_RELEASE_FAILED = "REQUEST_NEW_RELEASE_FAILED"

export const REQUEST_CURRENTLY_AIRING_PENDING = "REQUEST_CURRENTLY_AIRING_PENDING"
export const REQUEST_CURRENTLY_AIRING_SUCCESS = "REQUEST_CURRENTLY_AIRING_SUCCESS"
export const REQUEST_CURRENTLY_AIRING_FAILED = "REQUEST_CURRENTLY_AIRING_FAILED"

export const REQUEST_TV_SERIES_GENRES_PENDING = "REQUEST_TV_SERIES_GENRES_PENDING"
export const REQUEST_TV_SERIES_GENRES_SUCCESS = "REQUEST_TV_SERIES_GENRES_SUCCESS"
export const REQUEST_TV_SERIES_GENRES_FAILED = "REQUEST_TV_SERIES_GENRES_FAILED"

export const REQUEST_MOVIE_GENRES_PENDING = "REQUEST_MOVIE_GENRES_PENDING"
export const REQUEST_MOVIE_GENRES_SUCCESS = "REQUEST_MOVIE_GENRES_SUCCESS"
export const REQUEST_MOVIE_GENRES_FAILED = "REQUEST_MOVIE_GENRES_FAILED"